version: '3'

services:
  haproxy:
    depends_on:
      - cassandra
    container_name: ${COMPOSE_PROJECT_NAME}_haproxy
    build: ./haproxy
    networks:
      public_net:
        ipv4_address: ${HAPROXY_IP}
    ports:
      - "9042:9042" # Cassandra
    environment:
      - CASSANDRA_IP=${CASSANDRA_IP}
      - CASSANDRA_PORT=${CASSANDRA_PORT}
  cassandra:
    container_name: ${COMPOSE_PROJECT_NAME}_cassandra
    build: ./cassandra
    expose:
      - ${CASSANDRA_PORT}
    networks: 
      public_net:
        ipv4_address: ${CASSANDRA_IP}
networks:
  public_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}